version: '3.8'

services:
  bootstrap1:
    image: bootstrap_server:latest
    container_name: bootstrap1
    build:
      context: ./boot
      dockerfile: Dockerfile
    ports:
      - "1237:1237"
    command: [
      "./bootstrap_server",
      "-port=1237",
      "-key=0"
    ]
    networks:
      - bootstrap-net

  bootstrap2:
    image: bootstrap_server:latest
    container_name: bootstrap2
    build:
      context: ./boot
      dockerfile: Dockerfile
    ports:
      - "1238:1238"
    command: [
      "./bootstrap_server",
      "-port=1238",
      "-key=1",
      "-bootstrap=/dns4/bootstrap1/tcp/1237/p2p/12D3KooWLr1gYejUTeriAsSu6roR2aQ423G3Q4fFTqzqSwTsMz9n"
    ]
    depends_on:
      - bootstrap1
    networks:
      - bootstrap-net

  bootstrap3:
    image: bootstrap_server:latest
    container_name: bootstrap3
    build:
      context: ./boot
      dockerfile: Dockerfile
    ports:
      - "1239:1239"
    command: [
      "./bootstrap_server",
      "-port=1239",
      "-key=2",
      "-bootstrap=/dns4/bootstrap1/tcp/1237/p2p/12D3KooWLr1gYejUTeriAsSu6roR2aQ423G3Q4fFTqzqSwTsMz9n,/dns4/bootstrap2/tcp/1239/p2p/12D3KooWBnext3VBZZuBwGn3YahAZjf49oqYckfx64VpzH6dyU1p"
    ]
    depends_on:
      - bootstrap1
      - bootstrap2
    networks:
      - bootstrap-net

networks:
  bootstrap-net:
    driver: bridge
